Fix broken virt-install XML without "Immediately start VM"
Whenever there is an install phase (e.g. booting install media from an
iso or network and using that to install an OS into the guest),
virt-install will generate two slightly different guest
definitions: one for the very first boot (where the OS is installed to
the guest) and one for subsequent boots (after the OS is installed on
the guest). By default, --print-xml will print both the install phase
XML and the final XML, which resulted in a failure due to

    xml.etree.ElementTree.ParseError: junk after document element: line 61, column 0

Avoid that by only printing the XML for the first phase.

https://bugzilla.redhat.com/show_bug.cgi?id=2032462