Fix domainDetachHostDevice() for running VMs
Add missing `await`.
This previously caused an error:

> call is not a function or its return value is not iterable

https://issues.redhat.com/browse/RHEL-31082
RHEL 8.z-stream: https://issues.redhat.com/browse/RHEL-34694

Co-Authored-By: Martin Pitt <mpitt@redhat.com>

Cherry-picked from main commit c94885ac